export const errorMessages = {
  INCORRECT_PASSWORD: 'incorrectPassword',
  MISSING_FIELDS: 'missingFields',
  USER_NOT_FOUND: 'userNotFound',
  FAILED_TO_AUTHENTICATE: 'failedToAuthenticate',
  USER_ALREADY_EXIST: 'userAlreadyExist',
  PSEUDO_ALREADY_EXIST: 'pseudoAlreadyExist',
  SERVER_ERROR: 'somethingWentWrong',
  NOT_AUTHENTICATE: 'notAuthenticate',
  INVALID_LINK: 'invalidLink',
  EMAIL_ERROR: 'emailError',
  NOT_AUTHORIZED: 'notAuthorized',
  INVALID_CODE: 'invalidCode',
  INVALID_PACKAGE: 'invalidPackage',
  NO_UNPAID_SALES: 'noUnpaidSales',
  INSUFFICIENT_CREDITS: 'insufficientCredits',
  MISSING_BANK_ACCOUNT_INFORMATION: 'missingBankAccountInformation',
  NOT_FOUND: 'notFound',
  AUTH_REQUIRED: 'authRequired',
  UNAUTHORIZED: 'unauthorized',
  FANTASY_NOT_FOUND: 'fantasyNotFound',
  CHOICE_NOT_FOUND: 'choiceNotFound',
  INVALID_FANTASY: 'invalidFantasy',
  ALREADY_CLAIMED_THIS_WEEK: 'alreadyClaimedThisWeek',
};
